apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-helloworld
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-helloworld
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-helloworld
    spec:
      containers:
        - name: helloworld
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP